sylius_grid:
    grids:
        setono_sylius_log_entry_admin_log_entry:
            driver:
                name: doctrine/orm
                options:
                    repository:
                        method: createByOwnerIdQueryBuilder
                        arguments:
                            - $owner_id
            sorting:
                createdAt: desc
            limits: [1000]
            fields:
                level:
                    type: twig
                    label: setono_sylius_log_entry.ui.level
                    options:
                        template: "@SetonoSyliusLogEntryPlugin/Grid/Field/level.html.twig"
                        vars:
                            labels: "@SetonoSyliusLogEntryPlugin/Label/Level"
                message:
                    type: string
                    label: setono_sylius_log_entry.ui.message
                createdAt:
                    type: datetime
                    label: setono_sylius_log_entry.ui.created_at
                    options:
                        format: "Y-m-d H:i:s"
